In [1]:
#NUMPY ARRAYI OLUŞTURMAK 22.09.2020

In [2]:
import numpy as np 

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.array([3.14,4,5])

array([3.14, 4.  , 5.  ])

#numpyın sabit tip baskısı

In [6]:
np.array([3.14,4,5],dtype= "int")

array([3, 4, 5])

In [7]:
#sifirdan array oluşturma

In [8]:
np.zeros(10)
#10 tane 0 dan oluşan array oluşturur

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones((3,5))
#2 boyutlu ve birlerden oluşuyor
np.ones((3,5),dtype= int)
#type ı inte çevir

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [11]:
np.arange(0,31,3)
#0 dan 31 e 3er sayarak gidiyor

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [12]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
np.random.normal(10,4,(3,4))
#3 e 4 lük bir matristir bu verdiğimiz
#ortalaması 10 standart sapması 4 olacak şekilde oluşturabiliyoruz

array([[ 5.73984698, 11.73106087, 19.1673223 , 13.58297021],
       [17.32734434,  8.22499318, 17.49826663,  4.50296072],
       [14.6572642 , 15.34619211,  3.02309334,  7.06903973]])

In [14]:
#integerlardan rastegele
np.random.randint(0,10,(3,3))

array([[5, 4, 9],
       [8, 6, 9],
       [9, 3, 4]])

numpy devam işleri 23.09.2020

* ndim : boyut sayısı 
* shape : boyut bilgisi 
* size : toplam eleman sayısı
* dtype : array veri tipi
LETS BEGİNNNAAA
* **ARRAY ÖZELLİKLERİİİİİ**

In [15]:
import numpy as np
a = np.random.randint(10, size =10)
a

array([6, 2, 2, 7, 6, 4, 4, 0, 2, 3])

In [16]:
a[0]


6

In [17]:
a.ndim

1

In [18]:
a.shape
#tek boyutlu ve 10 adet elemanı oldugu anlamına gelen bir sonuc vermektedir

(10,)

In [19]:
a.size

10

In [20]:
a.dtype
#içerisindeki integerın tipini veriyorr

dtype('int32')

In [21]:
b = np.random.randint(10,size = (3,5))
b

array([[4, 8, 5, 9, 3],
       [6, 7, 5, 2, 4],
       [6, 9, 3, 3, 7]])

In [22]:
b.ndim

2

In [23]:
b.shape

(3, 5)

In [24]:
b.size

15

In [25]:
b.dtype

dtype('int32')

RESHAPİNG (YENİDEN SEKİLLENDİRME) 

In [26]:
import numpy as np 
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#amacım bu arrayden 3e 3 bir array elde etmek 
# nasıl reshape ederim shapeler arası
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a.ndim

1

In [30]:
b = a.reshape((1,9))
#1 boyuttan 2 boyutluya geçiş işlemi
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [31]:
b.ndim

2

Array birleştirme işlemi concatenation

In [32]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [33]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [34]:
z = np.array([7,8,9])

In [35]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#iki boyut için 
a = np.array([[1,2,3],
             [4,5,6]])

In [37]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
#sütun bazında birleştirelim axis e göre yapalımmm
np.concatenate([a,a],axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

SPLİT İŞLEMLERİ
ARRAY AYIRMA


In [39]:
x = np.array([1,2,3,99,99,3,2,1])

In [40]:
np.split(x,[3,5])
#2 index verince 3 adet array ayrılıyor n+1 şeklinde bir işlem 

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [41]:
a,b,c = np.split(x,[3,5])

In [42]:
a

array([1, 2, 3])

In [43]:
b

array([99, 99])

In [44]:
c

array([3, 2, 1])

In [45]:
#iki boyutlu ayırma işlemleri
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
#2.satırdan böl yana dikey ekle.
x,y = np.vsplit(m,[2])
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
y

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
#yatay versiyonunu deneyelim
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [50]:
h,j = np.split(m,[2])
h

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

SIRALAMA İŞLEMLERİ NUMPY

In [51]:
import numpy as np
v = np.array([2,3,5,6,1])
v

array([2, 3, 5, 6, 1])

In [52]:
np.sort(v)
#arrayın yapısı değişmedi
v

array([2, 3, 5, 6, 1])

In [53]:
#arrayın yapısı değişti
v.sort()

In [54]:
v

array([1, 2, 3, 5, 6])

In [55]:
#iki boyutlularda sıralama işlemleri 
np.random.normal(20,5 ,(3,3))

array([[21.14620791, 17.10513542, 16.09022065],
       [21.64843679, 26.39511342, 13.0017682 ],
       [18.62505698, 20.35450137, 29.52206543]])

In [56]:
#satır sıralama işlemleri
np.sort(m,axis=1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
np.sort(m,axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Numpy işlemleri 28.09
index ile eleman erişim işlemleri 

In [58]:
import numpy as np 
a = np.random.randint(10,size = 10)
a

array([2, 6, 6, 2, 6, 0, 2, 1, 2, 5])

In [59]:
a[0]

2

In [60]:
a[-1]
#tersten eleman erisimi

5

In [61]:
a[0]=100

In [62]:
a

array([100,   6,   6,   2,   6,   0,   2,   1,   2,   5])

In [63]:
m = np.random.randint(10,size = (3,5))
m

array([[8, 5, 3, 1, 6],
       [2, 1, 6, 5, 6],
       [0, 1, 8, 6, 7]])

In [64]:
m[0,0]

8

In [65]:
m[1,4]

6

In [66]:
m[1,4] = 99

In [67]:
m

array([[ 8,  5,  3,  1,  6],
       [ 2,  1,  6,  5, 99],
       [ 0,  1,  8,  6,  7]])

In [68]:
#numpy fixed type dır
m[1,4] = 2.2
#ondalıklı eklemedi
#yuvarlayarak integer ekleme yapıldı
#string için direk hata veriyor 

In [69]:
m

array([[8, 5, 3, 1, 6],
       [2, 1, 6, 5, 2],
       [0, 1, 8, 6, 7]])

Slicing ile elemanlara erişmek(Array Alt Kümelerine Erişim)

In [70]:
import numpy as np 
a= np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [71]:
a[0:3]
#aralıklı seçme işlemi

array([20, 21, 22])

In [72]:
a[:3]

array([20, 21, 22])

In [73]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [74]:
a[1::2]
#2 şer artarak ilerliyor 1.indexten itibaren 


array([21, 23, 25, 27, 29])

In [75]:
#2 boyutlu slice işlemleri 
m = np.random.randint(10,size = (5,5))
m

array([[0, 6, 8, 2, 3],
       [7, 2, 2, 5, 7],
       [4, 6, 1, 5, 8],
       [5, 7, 1, 2, 6],
       [1, 1, 2, 5, 0]])

In [76]:
m[:,0]
#1.sütuna erişim?

array([0, 7, 4, 5, 1])

In [77]:
m[2,:]
#2.satıra erişim

array([4, 6, 1, 5, 8])

In [78]:
m[0:2,0:3]

array([[0, 6, 8],
       [7, 2, 2]])

In [79]:
m[::,:2]
#m[:,0:2] aynı şey olurdu


array([[0, 6],
       [7, 2],
       [4, 6],
       [5, 7],
       [1, 1]])

In [80]:
m[1:3 , 0:2]

array([[7, 2],
       [4, 6]])

In [81]:
m

array([[0, 6, 8, 2, 3],
       [7, 2, 2, 5, 7],
       [4, 6, 1, 5, 8],
       [5, 7, 1, 2, 6],
       [1, 1, 2, 5, 0]])

Alt küme üzerinde işlem yapmak

In [82]:
import numpy as np 
a = np.random.randint(10, size = (5,5))
a

array([[0, 7, 5, 6, 6],
       [1, 4, 2, 7, 1],
       [3, 3, 7, 5, 8],
       [5, 7, 4, 4, 2],
       [5, 5, 7, 1, 0]])

In [83]:
altkume = a[0:3,0:2]
altkume


array([[0, 7],
       [1, 4],
       [3, 3]])

In [84]:
altkume[0,0] = 99
altkume[1,1] = 88

In [85]:
altkume

array([[99,  7],
       [ 1, 88],
       [ 3,  3]])

In [86]:
a

array([[99,  7,  5,  6,  6],
       [ 1, 88,  2,  7,  1],
       [ 3,  3,  7,  5,  8],
       [ 5,  7,  4,  4,  2],
       [ 5,  5,  7,  1,  0]])

In [87]:
#altkume ve a birlikte çalışıyor şuanda 
m = np.random.randint(10, size = (5,5))
m

array([[6, 7, 5, 4, 7],
       [1, 3, 1, 3, 6],
       [7, 8, 7, 3, 1],
       [9, 0, 4, 0, 2],
       [1, 0, 1, 9, 1]])

In [88]:
otheralt = m[0:3 , 0:2].copy()
otheralt

array([[6, 7],
       [1, 3],
       [7, 8]])

In [89]:
otheralt[0,0] = 99 

In [90]:
m

array([[6, 7, 5, 4, 7],
       [1, 3, 1, 3, 6],
       [7, 8, 7, 3, 1],
       [9, 0, 4, 0, 2],
       [1, 0, 1, 9, 1]])

In [91]:
otheralt
#copy işlemlerinden sonraki işlemlerana kümeden bağımsız olarak gerçekleşir.

array([[99,  7],
       [ 1,  3],
       [ 7,  8]])

FANCY İNDEX İLE ELEMANLARA ERİŞMEK

In [92]:
import numpy as np
v = np.arange (0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [93]:
v[1]

3

In [94]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [95]:
#bir fonk veya bir döngünün çıktısı çok fazla bilgi çıkarıyor ve istediğimi 
#yakalamaya calısıyorum dont think primarily think about fancy index
algetir = [1,3,5]

In [96]:
v[algetir]

array([ 3,  9, 15])

In [97]:
#this is not a special think its just an approach to searching in lists etc.
#you can easily reach what u seek for

#İKİ BOYUTTA FANCY
m = np.arange(9).reshape(3,3)

In [98]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [100]:
m[satir,sutun]

array([1, 5])

In [101]:
#basit index ile fancy index
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
m[0, [1,2]]

array([1, 2])

In [103]:
#slice ile birlikte fancy
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

Koşullu eleman işlemleri

In [104]:
import numpy as np
v = np.array ([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [105]:
v > 5
#her eleman için tek tek işler

array([False, False, False, False, False])

In [106]:
v < 3

array([ True,  True, False, False, False])

In [107]:
v[v<3]
#fancyli bir koşullu eleman işlemi


array([1, 2])

In [108]:
v[v > 3]

array([4, 5])

In [109]:
v[v<= 3]

array([1, 2, 3])

In [110]:
v[v == 3]

array([3])

In [111]:
v/4

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [112]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

MATEMATİKSEL İŞLEMLER 

In [113]:
v -1 

array([0, 1, 2, 3, 4])

In [114]:
#ufunc işlemleri
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [115]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [116]:
np.multiply(v,7)

array([ 7, 14, 21, 28, 35])

In [117]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [118]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [119]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [120]:
np.absolute(np.array([-3]))

array([3])

In [121]:
np.sin(360)

0.9589157234143065

In [122]:
np.cos(180)

-0.5984600690578581

In [123]:
v = np.array([1,2,3])

In [124]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [125]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [126]:
?np

Type:        module
String form: <module 'numpy' from 'D:\\python\\lib\\site-packages\\numpy\\__init__.py'>
File:        d:\python\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in `

In [127]:
#cheatsheet şeklinde arama yapabilirsin mesela numpy mathematics cheatsheet

Numpy ile iki bilinmeyenli denklem çözümü

In [128]:
import numpy as np 


5 * x0 + x1 = 12 
x0 + 3 * x1 = 10 


In [129]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [130]:
a

array([[5, 1],
       [1, 3]])

In [131]:
b

array([12, 10])

In [132]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

In [133]:
#tekrar çalışmaları

In [134]:
a[2,1]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [ ]:
a[0,0] = 1

In [ ]:
a

In [ ]:
a[1,1] = 2.2

In [ ]:
a[1,1] 

#Slicing işlemleri

In [ ]:
a = np.arange(20,30)
a

In [ ]:
a[0:3]

In [ ]:
a[:3]

In [ ]:
a[3:]

In [ ]:
a[::2]
#ikişer atlayarak gidiyor

In [ ]:
a[1::2]
#1 den basladıgı icin tek lerialıyor

In [ ]:
a = np.random.randint(10,size = (5,5))
a

In [ ]:
a[:,0]
#0ıncı sütun

In [ ]:
a[:,4]

In [ ]:
#satıra erişme

In [ ]:
a[0,:]

In [ ]:
a[4,:]

In [ ]:
#satır sütun beraber

In [ ]:
a[:2,:3]

In [ ]:
a[0:2,0:3]

In [ ]:
a[::,:2]

In [ ]:
a[:,:2]

In [ ]:
a[1:3,0:2]
#0 almamak için mesela?

#Array alt kümelerini bağımsızlaştırmak

In [ ]:
a = np.random.randint(10,size = (5,5))
a

In [ ]:
alt_a = a[0:3,0:2]

In [ ]:
alt_a

In [ ]:
alt_a[0,0] = 9999
alt_a[1,1] = 9999

In [ ]:
alt_a

In [ ]:
a

In [ ]:
a = np.random.randint(10,size = (5,5))
a

In [ ]:
alt_b = a[0:3,0:2].copy()

In [ ]:
alt_b

In [ ]:
alt_b[0,0]= 9999

In [ ]:
a

In [ ]:
#copy kullandığımızda kümeyi etkilemiyorz.

#FANCY index

In [ ]:
v = np.arange(0,30,3)

In [ ]:
v

In [ ]:
v[1],v[3]

In [ ]:
#slice da belli bir aralık vermiştik,fancyde ise birden fazla index seçimi için kullanıyoruz


In [ ]:
al_getir = [1,3,5]

In [ ]:
v[al_getir]

In [ ]:
m = np.arange(9).reshape((3,3))
m

In [ ]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [ ]:
m[satir,sutun]

In [ ]:
m[0,[1,2]]

In [ ]:
m[0:,[1,2]]
#0 dan hepsine sütunların içerisinden ise 1 ve 2 
#basit index slice ve fancy bir arada

In [ ]:
v = np.arange(10)
v

In [ ]:
index = np.array([0,1,2])
index

In [ ]:
v[index] = 99

In [ ]:
v

In [ ]:
v[[0,1]] = [4,6]
v

In [ ]:
#farklı bir concatenate yöntemi
import numpy as np 
a = np.array([[4,6],[5,7]])
b = np.array([[3,5],[1,2]])
a


In [ ]:
np.hstack((a,b))
#yanyana ekler satırları

In [ ]:
np.vstack((a,b))
#alt alta ekleme yapar

In [135]:
#string arrays
import numpy as np 
names = np.array(["susu","sonic","hemdem"],dtype=str)
names


array(['susu', 'sonic', 'hemdem'], dtype='<U6')

In [136]:
names[2]

'hemdem'

In [137]:

#structured array
data = np.array([
            ("joe", 32, 6),
            ("mary", 15, 20),
            ("felipe", 80, 100),
            ("beyonce", 38, 9001), ], 
    dtype=[("name", str, 10), ("age", int), ("power", int)])

In [138]:
data

array([('joe', 32,    6), ('mary', 15,   20), ('felipe', 80,  100),
       ('beyonce', 38, 9001)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('power', '<i4')])

In [139]:
data["name"]

array(['joe', 'mary', 'felipe', 'beyonce'], dtype='<U10')

In [141]:
#order by power
#similar to sql
#Select name From data where age>20 order by power
np.sort(data[data["age"] > 20], order="power")["name"]

array(['joe', 'felipe', 'beyonce'], dtype='<U10')