In [2]:
#NUMPY ARRAYI OLUŞTURMAK 22.09.2020

In [3]:
import numpy as np 

In [6]:
a = np.array([1,2,3,4,5])

In [7]:
type(a)

numpy.ndarray

In [8]:
np.array([3.14,4,5])

array([3.14, 4.  , 5.  ])

#numpyın sabit tip baskısı

In [11]:
np.array([3.14,4,5],dtype= "int")

array([3, 4, 5])

In [12]:
#sifirdan array oluşturma

In [14]:
np.zeros(10)
#10 tane 0 dan oluşan array oluşturur

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones((3,5))
#2 boyutlu ve birlerden oluşuyor
np.ones((3,5),dtype= int)
#type ı inte çevir

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [19]:
np.arange(0,31,3)
#0 dan 31 e 3er sayarak gidiyor

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [20]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [22]:
np.random.normal(10,4,(3,4))
#3 e 4 lük bir matristir bu verdiğimiz
#ortalaması 10 standart sapması 4 olacak şekilde oluşturabiliyoruz

array([[ 8.69046932,  8.47815185, 13.99200531,  6.65106111],
       [ 0.48373773, 10.85397164, 10.41295288,  7.14376553],
       [13.31152223, 10.48896745, 13.10356864,  9.54765646]])

In [23]:
#integerlardan rastegele
np.random.randint(0,10,(3,3))

array([[1, 7, 5],
       [4, 2, 8],
       [4, 4, 4]])

numpy devam işleri 23.09.2020

* ndim : boyut sayısı 
* shape : boyut bilgisi 
* size : toplam eleman sayısı
* dtype : array veri tipi
LETS BEGİNNNAAA
* **ARRAY ÖZELLİKLERİİİİİ**

In [2]:
import numpy as np
a = np.random.randint(10, size =10)
a

array([6, 8, 4, 5, 0, 6, 2, 5, 6, 3])

In [3]:
a[0]


6

In [5]:
a.ndim

1

In [7]:
a.shape
#tek boyutlu ve 10 adet elemanı oldugu anlamına gelen bir sonuc vermektedir

(10,)

In [8]:
a.size

10

In [9]:
a.dtype
#içerisindeki integerın tipini veriyorr

dtype('int32')

In [12]:
b = np.random.randint(10,size = (3,5))
b

array([[2, 1, 8, 9, 2],
       [6, 4, 5, 3, 0],
       [1, 7, 6, 5, 9]])

In [13]:
b.ndim

2

In [14]:
b.shape

(3, 5)

In [15]:
b.size

15

In [16]:
b.dtype

dtype('int32')

RESHAPİNG (YENİDEN SEKİLLENDİRME) 

In [17]:
import numpy as np 
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#amacım bu arrayden 3e 3 bir array elde etmek 
# nasıl reshape ederim shapeler arası lets see it baby
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a.ndim

1

In [25]:
b = a.reshape((1,9))
#1 boyuttan 2 boyutluya geçiş işlemisi
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
b.ndim

2

Array birleştirme işlemi concatenation

In [26]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [27]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [28]:
z = np.array([7,8,9])

In [29]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#iki boyut için 
a = np.array([[1,2,3],
             [4,5,6]])

In [33]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
#sütun bazında birleştirelim axis e göre yapalımmm
np.concatenate([a,a],axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

SPLİT İŞLEMLERİ
ARRAY AYIRMA


In [37]:
x = np.array([1,2,3,99,99,3,2,1])

In [38]:
np.split(x,[3,5])
#2 index verince 3 adet array ayrılıyor n+1 şeklinde bir işlem 

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [39]:
a,b,c = np.split(x,[3,5])

In [40]:
a

array([1, 2, 3])

In [41]:
b

array([99, 99])

In [42]:
c

array([3, 2, 1])

In [44]:
#iki boyutlu ayırma işlemleri
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
#2.satırdan böl yana dikey ekle.
x,y = np.vsplit(m,[2])
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [48]:
y

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
#yatay versiyonunu deneyelim
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [52]:
h,j = np.split(m,[2])
h

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

SIRALAMA İŞLEMLERİ NUMPY

In [53]:
import numpy as np
v = np.array([2,3,5,6,1])
v

array([2, 3, 5, 6, 1])

In [57]:
np.sort(v)
#arrayın yapısı değişmedi
v

array([1, 2, 3, 5, 6])

In [55]:
#arrayın yapısı değişti
v.sort()

In [56]:
v

array([1, 2, 3, 5, 6])

In [58]:
#iki boyutlularda sıralama işlemleri 
np.random.normal(20,5 ,(3,3))

array([[17.60698351, 20.80975688, 23.98879059],
       [19.61287731, 26.80243935, 24.8170755 ],
       [18.49888742, 20.35025154, 15.30144967]])

In [59]:
#satır sıralama işlemleri
np.sort(m,axis=1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
np.sort(m,axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Numpy işlemleri 28.09
index ile eleman erişim işlemleri 

In [2]:
import numpy as np 
a = np.random.randint(10,size = 10)
a

array([0, 4, 2, 5, 2, 5, 3, 0, 0, 6])

In [3]:
a[0]

0

In [4]:
a[-1]
#tersten eleman erisimi

6

In [5]:
a[0]=100

In [6]:
a

array([100,   4,   2,   5,   2,   5,   3,   0,   0,   6])

In [7]:
m = np.random.randint(10,size = (3,5))
m

array([[1, 2, 9, 4, 3],
       [4, 4, 0, 6, 7],
       [0, 0, 4, 4, 0]])

In [8]:
m[0,0]

1

In [10]:
m[1,4]

7

In [11]:
m[1,4] = 99

In [12]:
m

array([[ 1,  2,  9,  4,  3],
       [ 4,  4,  0,  6, 99],
       [ 0,  0,  4,  4,  0]])

In [14]:
#numpy fixed type dır
m[1,4] = 2.2
#ondalıklı eklemedi
#yuvarlayarak integer ekleme yapıldı
#string için direk hata veriyor 

In [15]:
m

array([[1, 2, 9, 4, 3],
       [4, 4, 0, 6, 2],
       [0, 0, 4, 4, 0]])

Slicing ile elemanlara erişmek(Array Alt Kümelerine Erişim)

In [17]:
import numpy as np 
a= np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
a[0:3]
#aralıklı seçme işlemi

array([20, 21, 22])

In [19]:
a[:3]

array([20, 21, 22])

In [20]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [22]:
a[1::2]
#2 şer artarak ilerliyor 1.indexten itibaren 


array([21, 23, 25, 27, 29])

In [23]:
#2 boyutlu slice işlemleri 
m = np.random.randint(10,size = (5,5))
m

array([[6, 9, 3, 6, 0],
       [2, 4, 4, 4, 4],
       [7, 0, 8, 7, 1],
       [6, 7, 6, 8, 4],
       [7, 1, 2, 9, 7]])

In [24]:
m[:,0]
#1.sütuna erişim?

array([6, 2, 7, 6, 7])

In [25]:
m[2,:]
#2.satıra erişim

array([7, 0, 8, 7, 1])

In [26]:
m[0:2,0:3]

array([[6, 9, 3],
       [2, 4, 4]])

In [28]:
m[::,:2]
#m[:,0:2] aynı şey olurdu


array([[6, 9],
       [2, 4],
       [7, 0],
       [6, 7],
       [7, 1]])

In [29]:
m[1:3 , 0:2]

array([[2, 4],
       [7, 0]])

In [30]:
m

array([[6, 9, 3, 6, 0],
       [2, 4, 4, 4, 4],
       [7, 0, 8, 7, 1],
       [6, 7, 6, 8, 4],
       [7, 1, 2, 9, 7]])

Alt küme üzerinde işlem yapmak

In [31]:
import numpy as np 
a = np.random.randint(10, size = (5,5))
a

array([[9, 4, 6, 5, 6],
       [0, 3, 0, 5, 0],
       [6, 2, 8, 2, 6],
       [8, 9, 2, 9, 2],
       [9, 7, 2, 6, 9]])

In [32]:
altkume = a[0:3,0:2]
altkume


array([[9, 4],
       [0, 3],
       [6, 2]])

In [34]:
altkume[0,0] = 99
altkume[1,1] = 88

In [35]:
altkume

array([[99,  4],
       [ 0, 88],
       [ 6,  2]])

In [36]:
a

array([[99,  4,  6,  5,  6],
       [ 0, 88,  0,  5,  0],
       [ 6,  2,  8,  2,  6],
       [ 8,  9,  2,  9,  2],
       [ 9,  7,  2,  6,  9]])

In [37]:
#altkume ve a birlikte çalışıyor şuanda 
m = np.random.randint(10, size = (5,5))
m

array([[2, 1, 5, 4, 2],
       [8, 2, 1, 8, 8],
       [5, 0, 1, 0, 7],
       [5, 0, 1, 1, 9],
       [0, 4, 8, 7, 2]])

In [39]:
otheralt = m[0:3 , 0:2].copy()
otheralt

array([[2, 1],
       [8, 2],
       [5, 0]])

In [40]:
otheralt[0,0] = 99 

In [41]:
m

array([[2, 1, 5, 4, 2],
       [8, 2, 1, 8, 8],
       [5, 0, 1, 0, 7],
       [5, 0, 1, 1, 9],
       [0, 4, 8, 7, 2]])

In [42]:
otheralt
#copy işlemlerinden sonraki işlemlerana kümeden bağımsız olarak gerçekleşir.

array([[99,  1],
       [ 8,  2],
       [ 5,  0]])

FANCY İNDEX İLE ELEMANLARA ERİŞMEK

In [44]:
import numpy as np
v = np.arange (0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [45]:
v[1]

3

In [46]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [47]:
#bir fonk veya bir döngünün çıktısı çok fazla bilgi çıkarıyor ve istediğimi 
#yakalamaya calısıyorum dont think primarily think about fancy index
algetir = [1,3,5]

In [48]:
v[algetir]

array([ 3,  9, 15])

In [50]:
#this is not a special think its just an approach to searching in lists etc.
#you can easily reach what u seek for

#İKİ BOYUTTA FANCY
m = np.arange(9).reshape(3,3)

In [51]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [53]:
m[satir,sutun]

array([1, 5])

In [54]:
#basit index ile fancy index
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
m[0, [1,2]]

array([1, 2])

In [56]:
#slice ile birlikte fancy
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

Koşullu eleman işlemleri

In [58]:
import numpy as np
v = np.array ([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [59]:
v > 5
#her eleman için tek tek işler

array([False, False, False, False, False])

In [60]:
v < 3

array([ True,  True, False, False, False])

In [61]:
v[v<3]
#fancyli bir kşullu eleman işlemisi


array([1, 2])

In [62]:
v[v > 3]

array([4, 5])

In [63]:
v[v<= 3]

array([1, 2, 3])

In [64]:
v[v == 3]

array([3])

In [65]:
v/4

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [66]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

MATEMATİKSEL İŞLEMLER 

In [67]:
v -1 

array([0, 1, 2, 3, 4])

In [68]:
#ufunc işlemleri
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [69]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [71]:
np.multiply(v,7)

array([ 7, 14, 21, 28, 35])

In [72]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [73]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [74]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [76]:
np.absolute(np.array([-3]))

array([3])

In [77]:
np.sin(360)

0.9589157234143065

In [78]:
np.cos(180)

-0.5984600690578581

In [79]:
v = np.array([1,2,3])

In [80]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [81]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [82]:
?np

Type:        module
String form: <module 'numpy' from 'D:\\python\\lib\\site-packages\\numpy\\__init__.py'>
File:        d:\python\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in `

In [83]:
#cheatsheet şeklinde arama yapabilirsin mesela numpy mathematics cheatsheet

Numpy ile iki bilinmeyenli denklem çözümü

In [84]:
import numpy as np 


5 * x0 + x1 = 12 
x0 + 3 * x1 = 10 


In [85]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [86]:
a

array([[5, 1],
       [1, 3]])

In [87]:
b

array([12, 10])

In [89]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

In [16]:
a[2,1]

9

In [12]:
a[0,0] = 1

In [13]:
a

array([[1, 9, 6, 7, 0],
       [5, 0, 2, 8, 4],
       [9, 9, 5, 5, 8]])

In [15]:
a[1,1] = 2.2

In [17]:
a[1,1] 

2

#Slicing işlemleri

In [19]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
a[0:3]

array([20, 21, 22])

In [21]:
a[:3]

array([20, 21, 22])

In [23]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [24]:
a[::2]
#ikişer atlayarak gidiyor

array([20, 22, 24, 26, 28])

In [25]:
a[1::2]
#1 den basladıgı icin tek lerialıyor

array([21, 23, 25, 27, 29])

In [26]:
a = np.random.randint(10,size = (5,5))
a

array([[9, 0, 3, 8, 8],
       [7, 9, 1, 0, 1],
       [5, 7, 0, 9, 8],
       [2, 5, 3, 9, 0],
       [5, 3, 0, 1, 8]])

In [28]:
a[:,0]
#0ıncı sütun

array([9, 7, 5, 2, 5])

In [29]:
a[:,4]

array([8, 1, 8, 0, 8])

In [33]:
#satıra erişme

In [31]:
a[0,:]

array([9, 0, 3, 8, 8])

In [32]:
a[4,:]

array([5, 3, 0, 1, 8])

In [ ]:
#satır sütun beraber

In [34]:
a[:2,:3]

array([[9, 0, 3],
       [7, 9, 1]])

In [35]:
a[0:2,0:3]

array([[9, 0, 3],
       [7, 9, 1]])

In [36]:
a[::,:2]

array([[9, 0],
       [7, 9],
       [5, 7],
       [2, 5],
       [5, 3]])

In [37]:
a[:,:2]

array([[9, 0],
       [7, 9],
       [5, 7],
       [2, 5],
       [5, 3]])

In [38]:
a[1:3,0:2]
#0 almamak için mesela?

array([[7, 9],
       [5, 7]])

#Array alt kümelerini bağımsızlaştırmak

In [39]:
a = np.random.randint(10,size = (5,5))
a

array([[5, 4, 5, 6, 0],
       [8, 6, 4, 2, 3],
       [9, 7, 0, 0, 9],
       [4, 8, 3, 1, 6],
       [5, 3, 0, 9, 1]])

In [40]:
alt_a = a[0:3,0:2]

In [41]:
alt_a

array([[5, 4],
       [8, 6],
       [9, 7]])

In [42]:
alt_a[0,0] = 9999
alt_a[1,1] = 9999

In [43]:
alt_a

array([[9999,    4],
       [   8, 9999],
       [   9,    7]])

In [44]:
a

array([[9999,    4,    5,    6,    0],
       [   8, 9999,    4,    2,    3],
       [   9,    7,    0,    0,    9],
       [   4,    8,    3,    1,    6],
       [   5,    3,    0,    9,    1]])

In [49]:
a = np.random.randint(10,size = (5,5))
a

array([[8, 8, 5, 1, 3],
       [4, 7, 3, 5, 8],
       [2, 9, 5, 7, 0],
       [5, 9, 5, 1, 8],
       [8, 5, 5, 5, 8]])

In [50]:
alt_b = a[0:3,0:2].copy()

In [51]:
alt_b

array([[8, 8],
       [4, 7],
       [2, 9]])

In [52]:
alt_b[0,0]= 9999

In [53]:
a

array([[8, 8, 5, 1, 3],
       [4, 7, 3, 5, 8],
       [2, 9, 5, 7, 0],
       [5, 9, 5, 1, 8],
       [8, 5, 5, 5, 8]])

In [ ]:
#copy kullandığımızda kümeyi etkilemiyorz.

#FANCY index

In [54]:
v = np.arange(0,30,3)

In [55]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [56]:
v[1],v[3]

(3, 9)

In [57]:
#slice da belli bir aralık vermiştik,fancyde ise birden fazla index seçimi için kullanıyoruz


In [59]:
al_getir = [1,3,5]

In [60]:
v[al_getir]

array([ 3,  9, 15])

In [62]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [64]:
m[satir,sutun]

array([1, 5])

In [65]:
m[0,[1,2]]

array([1, 2])

In [67]:
m[0:,[1,2]]
#0 dan hepsine sütunların içerisinden ise 1 ve 2 
#basit index slice ve fancy bir arada

array([[1, 2],
       [4, 5],
       [7, 8]])

In [68]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
index = np.array([0,1,2])
index

array([0, 1, 2])

In [70]:
v[index] = 99

In [72]:
v

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [73]:
v[[0,1]] = [4,6]
v

array([ 4,  6, 99,  3,  4,  5,  6,  7,  8,  9])