PANDASSSSSSSSSSSSSSSSSSS

In [2]:
import pandas as pd

In [3]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
seri = pd.Series([1,2,3])

In [5]:
type(seri)

pandas.core.series.Series

In [6]:
seri.axes
#serinin index bilgileri

[RangeIndex(start=0, stop=3, step=1)]

In [7]:
seri.dtype


dtype('int64')

In [8]:
seri.size

3

In [9]:
seri.ndim

1

In [10]:
seri.values

array([1, 2, 3], dtype=int64)

In [11]:
seri.head()

0    1
1    2
2    3
dtype: int64

In [12]:
seri.head(2)

0    1
1    2
dtype: int64

In [13]:
seri.tail(1)

2    3
dtype: int64

In [14]:
#index isimlendirmesi
pd.Series([25,36,49,51])

0    25
1    36
2    49
3    51
dtype: int64

In [15]:
pd.Series([25,36,49,51] , index = [1,3,5,7])

1    25
3    36
5    49
7    51
dtype: int64

In [17]:
seri = pd.Series([25,36,49,51] , index = ["a","b","c","d"])

In [18]:
seri

a    25
b    36
c    49
d    51
dtype: int64

In [19]:
seri["a"]

25

In [21]:
seri["a":"c"]

a    25
b    36
c    49
dtype: int64

In [22]:
#sozluk üzerinden liste oluşturmak

In [23]:
sozluk = pd.Series({"reg":10 , "log": 11 , "cart": 12})

In [24]:
sozluk

reg     10
log     11
cart    12
dtype: int64

In [25]:
seri = pd.Series(sozluk)

In [26]:
seri

reg     10
log     11
cart    12
dtype: int64

In [27]:
#iki seriyi birleştirerek seri oluşturma.
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

In [28]:
#seriler array gibi düsünülmelidir yan yana eklenemezler.

ELeman İşlemleri

In [30]:
import pandas as pd
import numpy as np

In [33]:
a = np.array([1,2,3,4,5])
a
seri = pd.Series(a)
seri

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [34]:
seri[0]

1

In [35]:
seri[0:3]
#3 e kadar slicingi

0    1
1    2
2    3
dtype: int32

In [36]:
seri = pd.Series([121,200,50,99] , index = ["reg","log","cart","rf"])

In [37]:
seri

reg     121
log     200
cart     50
rf       99
dtype: int64

In [38]:
seri.index

Index(['reg', 'log', 'cart', 'rf'], dtype='object')

In [39]:
seri.keys

<bound method Series.keys of reg     121
log     200
cart     50
rf       99
dtype: int64>

In [41]:
list(seri.items())
#itemleri ayrı ayrı görebilmek için

[('reg', 121), ('log', 200), ('cart', 50), ('rf', 99)]

In [42]:
seri.values

array([121, 200,  50,  99], dtype=int64)

In [43]:
#eleman sorgulama 
"reg" in seri

True

In [44]:
"a" in seri

False

In [46]:
seri["reg"]

121

In [47]:
#fancy eleman
seri[["rf","reg"]]

rf      99
reg    121
dtype: int64

In [48]:
#değişim yapalım
seri["reg"] = 19203

In [49]:
seri["reg"]

19203

In [50]:
seri ["reg": "log"]

reg    19203
log      200
dtype: int64

 PANDAS DATAFRAME OLUŞTURMA

In [51]:
#EXCELE BENZER Bİ YAPIDIR.
import pandas as pd 

In [56]:
l = [1,2,3]

In [55]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2              3

In [60]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [63]:
#df isimlendirme
df = pd.DataFrame(m ,  columns = ["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [66]:
df.columns = ("deg1","deg2","deg3")
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [67]:
type(df)

pandas.core.frame.DataFrame

In [68]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [69]:
df.shape

(3, 3)

In [70]:
df.ndim

2

In [71]:
df.size

9

In [72]:
df.values
#numpy arrayine çevirdi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
type(df.values)

numpy.ndarray

In [74]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [79]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [77]:
a= np.array([1,2,3,4,5])

In [78]:
pd.DataFrame(a , columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

Eleman İşlemleri devam

In [106]:
import numpy as np 
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [107]:
sozluk = {"var1" : s1, "var2" : s2 , "var3" : s3}
sozluk

{'var1': array([8, 2, 5, 5, 9]),
 'var2': array([7, 1, 1, 1, 0]),
 'var3': array([4, 0, 4, 8, 7])}

In [108]:
df = pd.DataFrame(sozluk)

In [109]:
df

var1  var2  var3
0     8     7     4
1     2     1     0
2     5     1     4
3     5     1     8
4     9     0     7

In [110]:
df[0:1]

var1  var2  var3
0     8     7     4

In [111]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [112]:
df.index = ["a", "b", "c" ,"d" ,"e"]

In [113]:
df

var1  var2  var3
a     8     7     4
b     2     1     0
c     5     1     4
d     5     1     8
e     9     0     7

In [114]:
df["c":"e"]

var1  var2  var3
c     5     1     4
d     5     1     8
e     9     0     7

In [115]:
#silme işlemi
df.drop("a",axis = 0)

var1  var2  var3
b     2     1     0
c     5     1     4
d     5     1     8
e     9     0     7

In [116]:
df

var1  var2  var3
a     8     7     4
b     2     1     0
c     5     1     4
d     5     1     8
e     9     0     7

In [117]:
#değişiklliği kaydeder
df.drop("a", axis = 0 , inplace = True)


In [118]:
df

var1  var2  var3
b     2     1     0
c     5     1     4
d     5     1     8
e     9     0     7

In [119]:
#fancy 
l = ["c", "e"]


In [120]:
df.drop(l, axis = 0 ,inplace = True)

In [121]:
df

var1  var2  var3
b     2     1     0
d     5     1     8

In [122]:
#degiskenler icin 
"var1" in df

True

In [123]:
l = ["var1","var4","var3"]

In [124]:
for i in l : 
    print(i in df)

True
False
True


In [125]:
df 

var1  var2  var3
b     2     1     0
d     5     1     8

In [126]:
df["var1"]

b    2
d    5
Name: var1, dtype: int32

In [127]:
df["var4"]  = df["var2"] * df["var1"]

In [128]:
df

var1  var2  var3  var4
b     2     1     0     2
d     5     1     8     5

In [129]:
#degisken silme
df.drop("var3", axis =1 )

var1  var2  var4
b     2     1     2
d     5     1     5

In [130]:
df

var1  var2  var3  var4
b     2     1     0     2
d     5     1     8     5

In [131]:
df.drop("var3",axis = 1 , inplace= True)


In [132]:
df

var1  var2  var4
b     2     1     2
d     5     1     5

In [133]:
l = ["var1","var2"]

In [134]:
df.drop(l,axis = 1 )

var4
b     2
d     5

In [135]:
df

var1  var2  var4
b     2     1     2
d     5     1     5